# Generated by Django 2.2 on 2019-04-17 07:48

import datetime

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('Tick_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name = 'Salesman',
            fields = [
                ('customer_ptr',
                 models.OneToOneField(auto_created = True, on_delete = django.db.models.deletion.CASCADE,
                                      parent_link = True, primary_key = True, serialize = False,
                                      to = settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(upload_to = '')),
            ],
            options = {
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases = ('Tick_server.customer',),
            managers = [
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name = 'discount',
            name = 'expire_date',
            field = models.DateField(default = datetime.datetime(2019, 4, 17, 7, 48, 0, 781078, tzinfo = utc)),
        ),
    ]
