# Generated by Django 2.2 on 2019-05-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tick_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateproduct',
            name='count',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='candidateproduct',
            name='expire_date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='candidateproduct',
            name='percent',
            field=models.CharField(max_length=3),
        ),
    ]
