# Generated by Django 2.2 on 2019-04-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Tick_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'customuser',
            name = 'user_type',
            field = models.CharField(choices = [('SU', 'Super User'), ('CU', 'Customer'), ('SM', 'Salesman')],
                                     max_length = 2),
        ),
    ]
