# Generated by Django 2.2 on 2019-05-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tick_server', '0002_auto_20190508_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tick_server.ShopKind'),
        ),
    ]
