# Generated by Django 2.2 on 2019-04-17 07:49

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('Tick_server', '0002_auto_20190417_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'discount',
            name = 'expire_date',
            field = models.DateField(default = datetime.datetime(2019, 4, 17, 7, 49, 8, 736849, tzinfo = utc)),
        ),
    ]
