# Generated by Django 2.2 on 2019-05-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tick_server', '0002_auto_20190515_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateproduct',
            name='count',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='candidateproduct',
            name='expire_date',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='candidateproduct',
            name='percent',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='checkboxpoll',
            name='importance',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='linearscalepoll',
            name='importance',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='multiplechoicepoll',
            name='importance',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='paragraphpoll',
            name='importance',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='shortanswerpoll',
            name='importance',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
