# Generated by Django 2.2 on 2019-04-17 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Tick_server', '0003_auto_20190417_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'discount',
            name = 'expire_date',
            field = models.DateField(default = django.utils.timezone.now),
        ),
    ]
