# Generated by Django 2.2 on 2019-05-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tick_server', '0003_auto_20190508_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='business_license',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
