# Generated by Django 2.2 on 2019-05-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tick_server', '0003_auto_20190515_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesman',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
