# Generated by Django 2.2 on 2019-04-18 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Tick_server', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name = 'Salesman',
            fields = [
                ('id',
                 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('avatar', models.ImageField(upload_to = '')),
                ('user',
                 models.OneToOneField(on_delete = django.db.models.deletion.CASCADE, to = settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
