# Generated by Django 2.2 on 2019-05-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tick_server', '0004_auto_20190508_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
