# Generated by Django 2.2 on 2019-05-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tick_server', '0005_auto_20190508_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tick_server.Salesman'),
        ),
    ]
