# Generated by Django 2.2 on 2019-04-28 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Tick_server', '0005_auto_20190419_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'customuser',
            name = 'is_superuser',
            field = models.BooleanField(default = False,
                                        help_text = 'Designates that this user has all permissions without explicitly assigning them.',
                                        verbose_name = 'superuser status'),
        ),
        migrations.AlterField(
            model_name = 'customer',
            name = 'user',
            field = models.OneToOneField(on_delete = django.db.models.deletion.CASCADE, related_name = 'customer',
                                         to = settings.AUTH_USER_MODEL),
        ),
    ]
