# Generated by Django 2.2 on 2019-05-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tick_server', '0006_shop_salesman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='Tick_server.Customer'),
        ),
    ]
