# Generated by Django 2.2 on 2019-04-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Tick_server', '0006_auto_20190428_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name = 'Code4DigitSalesman',
            fields = [
                ('id',
                 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('email', models.EmailField(max_length = 254)),
                ('code', models.CharField(max_length = 4)),
                ('password', models.CharField(max_length = 50)),
            ],
        ),
    ]
